### ISSUE TITLE
zh_CN. json

### ISSUE THREAD

**Issue by rentommy** [AmyMialeeMods/double-jump-attribute#1]
{
  "item.doublejumpattribute.jump_boots" : "跳跃靴",
  "attribute.doublejumpattribute.jumps" : "额外跳跃",
  "subtitles.doublejumpattribute.jump" : "两段跳跃"
}

**Comment by AmyMialee** [comment]
Thanks!

**Comment by AmyMialee** [comment]
https://github.com/AmyMialeeMods/double-jump-attribute/releases/tag/v1.0.4
